# Generated by Django 4.1.7 on 2023-05-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_alter_product_options_product_discount'),
        ('cart', '0002_rename_products_cart_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(related_name='liked_products', to='main_app.product')),
            ],
        ),
    ]
