# Generated by Django 4.1.7 on 2023-04-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_sub_category_category_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub',
        ),
        migrations.AddField(
            model_name='category',
            name='sub',
            field=models.ManyToManyField(related_name='subs', to='main_app.sub_category'),
        ),
    ]
