# Generated by Django 4.1.7 on 2023-04-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_category_sub_category_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub',
            field=models.ManyToManyField(null=True, related_name='subs', to='main_app.sub_category'),
        ),
    ]
