# Generated by Django 4.1.7 on 2023-04-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_category_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub',
        ),
        migrations.DeleteModel(
            name='Sub_category',
        ),
    ]
