# Generated by Django 4.1.7 on 2023-04-06 07:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_category_sub_delete_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_img',
            old_name='name',
            new_name='image',
        ),
        migrations.AddField(
            model_name='color',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 4, 6, 7, 35, 45, 721645, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
