# Generated by Django 4.1.7 on 2023-04-06 07:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_name_product_img_image_color_slug_size_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_img',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_img',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 4, 6, 7, 38, 8, 663216, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
