# Generated by Django 4.1.7 on 2023-04-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_product_img_alter_category_slug_alter_color_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_img',
            name='name',
        ),
        migrations.AddField(
            model_name='product_img',
            name='name',
            field=models.ManyToManyField(related_name='products', to='main_app.product'),
        ),
    ]
