# Generated by Django 4.1.7 on 2023-04-14 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_product_img_name_product_img_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_img',
            name='name',
        ),
        migrations.AddField(
            model_name='product_img',
            name='name',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='product_img', to='main_app.product'),
            preserve_default=False,
        ),
    ]
