# Generated by Django 4.1.7 on 2023-04-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_img',
            name='slug',
        ),
    ]
