# Generated by Django 4.1.7 on 2023-04-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_product_img_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_img',
            old_name='name',
            new_name='product',
        ),
    ]
